### ISSUE TITLE
Request: hide cmd windows

### ISSUE THREAD

**Issue by fenomeno83** [AerisG222/NDCRaw#1]
Hi. When I use DCRAW to write tiff file from raw input
_//example code_
_var dcraw = new DCRaw(new DCRawOptions() { Format = Format.Tiff, DCRawPath ="dcraw.exe" });
var outfile = dcraw.Convert(filename);_

will apper cmd command window.

Is it possibile hide it? (similar to _UseShellExecute = false and CreateNoWindow = true_ in ProcessStartInfo when use Process.Start in c#

Thanks

**Comment by AerisG222** [comment]
resolved in v.0.5.2 as a part of shifting to [MedallionShell](https://github.com/madelson/MedallionShell).
